winget install -e --accept-package-agreements --accept-source-agreements --id Prusa3D.PrusaSlicer
winget install -e --accept-package-agreements --accept-source-agreements --id Ultimaker.Cura
winget install -e --accept-package-agreements --accept-source-agreements --id Mozilla.Firefox
winget install -e --accept-package-agreements --accept-source-agreements --id Notepad++.Notepad++
winget install -e --accept-package-agreements --accept-source-agreements --id Microsoft.VisualStudioCode
winget install -e --accept-package-agreements --accept-source-agreements --id Valve.Steamwinget 
winget install -e --accept-package-agreements --accept-source-agreements --id suse.RancherDesktop
winget install -e --accept-package-agreements --accept-source-agreements --id mRemoteNG.mRemoteNG
winget install -e --accept-package-agreements --accept-source-agreements --id Greenshot.Greenshot
winget install -e --accept-package-agreements --accept-source-agreements --id Joplin.Joplin
winget install -e --accept-package-agreements --accept-source-agreements --id GitHub.GitHubDesktop
winget install -e --accept-package-agreements --accept-source-agreements --id Discord.Discord
winget install -e --accept-package-agreements --accept-source-agreements --id RocketChat.RocketChat
winget install -e --accept-package-agreements --accept-source-agreements --id Mirantis.Lens
winget install -e --accept-package-agreements --accept-source-agreements --id 7zip.7zip
#winget install -e --accept-package-agreements --accept-source-agreements --id EpicGames.EpicGamesLauncher
winget install -e --accept-package-agreements --accept-source-agreements --id Git.Git
winget install -e --accept-package-agreements --accept-source-agreements --id Inkscape.Inkscape
winget install -e --accept-package-agreements --accept-source-agreements --id FreeCAD.FreeCAD
winget install -e --accept-package-agreements --accept-source-agreements --id PrivateInternetAccess.PrivateInternetAccess
winget install -e --accept-package-agreements --accept-source-agreements --id WireGuard.WireGuard
winget install -e --accept-package-agreements --accept-source-agreements --id OBSProject.OBSStudio
winget install -e --accept-package-agreements --accept-source-agreements --id VideoLAN.VLC